import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { SessionProvider } from "next-auth/react"
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={`${inter.className}`} suppressHydrationWarning>
       <SessionProvider> <NuqsAdapter>{children}</NuqsAdapter></SessionProvider>
      </body>
    </html>
  );
}