import { Article, Category, Collection, Client, SalesData, CategoryStats, ArticleVariant, AttributeTemplate } from './types';

export const categories: Category[] = [
  {
    id: '1',
    name: 'Électronique',
    description: 'Appareils et gadgets électroniques',
    createdAt: new Date('2024-01-15'),
    isActive: true,
  },
  {
    id: '2',
    name: 'Vêtements',
    description: 'Mode et accessoires vestimentaires',
    createdAt: new Date('2024-01-20'),
    isActive: true,
  },
  {
    id: '3',
    name: 'Maison & Jardin',
    description: 'Articles pour la maison et le jardin',
    createdAt: new Date('2024-02-01'),
    isActive: true,
  },
];

export const collections: Collection[] = [
  {
    id: '1',
    name: 'Collection Printemps 2024',
    description: 'Nouveautés de la saison printemps',
    season: 'Printemps',
    createdAt: new Date('2024-03-01'),
    isActive: true,
  },
  {
    id: '2',
    name: 'Collection Été 2024',
    description: 'Articles d\'été tendance',
    season: 'Été',
    createdAt: new Date('2024-06-01'),
    isActive: true,
  },
  {
    id: '3',
    name: 'Collection Automne 2024',
    description: 'Essentiels pour l\'automne',
    season: 'Automne',
    createdAt: new Date('2024-09-01'),
    isActive: true,
  },
];

export const attributeTemplates: AttributeTemplate[] = [
  {
    id: '1',
    name: 'Couleur',
    type: 'color',
    values: ['Rouge', 'Bleu', 'Vert', 'Noir', 'Blanc', 'Jaune', 'Rose', 'Violet'],
    isRequired: true,
  },
  {
    id: '2',
    name: 'Taille',
    type: 'size',
    values: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    isRequired: true,
  },
  {
    id: '3',
    name: 'Matériau',
    type: 'material',
    values: ['Coton', 'Polyester', 'Laine', 'Soie', 'Lin', 'Cuir', 'Plastique', 'Métal'],
    isRequired: false,
  },
  {
    id: '4',
    name: 'Style',
    type: 'style',
    values: ['Classique', 'Moderne', 'Vintage', 'Sport', 'Décontracté', 'Élégant'],
    isRequired: false,
  },
];

const articleVariants: ArticleVariant[] = [
  // Variants pour Smartphone Premium XZ
  {
    id: 'v1',
    articleId: '1',
    name: 'Smartphone Premium XZ - Noir 128GB',
    sku: 'SPX-BLK-128',
    price: 899.99,
    stock: 15,
    isDefault: true,
    attributes: [
      { id: 'a1', name: 'Couleur', value: 'Noir', type: 'color', hexColor: '#000000' },
      { id: 'a2', name: 'Stockage', value: '128GB', type: 'custom' },
    ],
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-12-01'),
    isActive: true,
  },
  {
    id: 'v2',
    articleId: '1',
    name: 'Smartphone Premium XZ - Blanc 256GB',
    sku: 'SPX-WHT-256',
    price: 999.99,
    stock: 10,
    isDefault: false,
    attributes: [
      { id: 'a3', name: 'Couleur', value: 'Blanc', type: 'color', hexColor: '#FFFFFF' },
      { id: 'a4', name: 'Stockage', value: '256GB', type: 'custom' },
    ],
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-12-01'),
    isActive: true,
  },
  // Variants pour T-Shirt Coton Bio
  {
    id: 'v3',
    articleId: '2',
    name: 'T-Shirt Coton Bio - Rouge M',
    sku: 'TCB-RED-M',
    price: 29.99,
    stock: 25,
    isDefault: true,
    attributes: [
      { id: 'a5', name: 'Couleur', value: 'Rouge', type: 'color', hexColor: '#FF0000' },
      { id: 'a6', name: 'Taille', value: 'M', type: 'size' },
      { id: 'a7', name: 'Matériau', value: 'Coton', type: 'material' },
    ],
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-11-28'),
    isActive: true,
  },
  {
    id: 'v4',
    articleId: '2',
    name: 'T-Shirt Coton Bio - Bleu L',
    sku: 'TCB-BLU-L',
    price: 29.99,
    stock: 30,
    isDefault: false,
    attributes: [
      { id: 'a8', name: 'Couleur', value: 'Bleu', type: 'color', hexColor: '#0000FF' },
      { id: 'a9', name: 'Taille', value: 'L', type: 'size' },
      { id: 'a10', name: 'Matériau', value: 'Coton', type: 'material' },
    ],
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-11-28'),
    isActive: true,
  },
  {
    id: 'v5',
    articleId: '2',
    name: 'T-Shirt Coton Bio - Noir S',
    sku: 'TCB-BLK-S',
    price: 29.99,
    stock: 45,
    isDefault: false,
    attributes: [
      { id: 'a11', name: 'Couleur', value: 'Noir', type: 'color', hexColor: '#000000' },
      { id: 'a12', name: 'Taille', value: 'S', type: 'size' },
      { id: 'a13', name: 'Matériau', value: 'Coton', type: 'material' },
    ],
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-11-28'),
    isActive: true,
  },
];

export const articles: Article[] = [
  {
    id: '1',
    title: 'Smartphone Premium XZ',
    description: 'Dernier modèle de smartphone avec caméra 108MP et écran OLED',
    basePrice: 899.99,
    categoryId: '1',
    collectionId: '2',
    image: 'https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg',
    likes: 156,
    createdAt: new Date('2024-06-15'),
    updatedAt: new Date('2024-12-01'),
    isActive: true,
    variants: articleVariants.filter(v => v.articleId === '1'),
  },
  {
    id: '2',
    title: 'T-Shirt Coton Bio',
    description: 'T-shirt en coton biologique, confortable et écologique',
    basePrice: 29.99,
    categoryId: '2',
    collectionId: '1',
    image: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg',
    likes: 89,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-11-28'),
    isActive: true,
    variants: articleVariants.filter(v => v.articleId === '2'),
  },
  {
    id: '3',
    title: 'Pot de Fleurs Design',
    description: 'Pot de fleurs moderne en céramique avec drainage intégré',
    basePrice: 24.99,
    categoryId: '3',
    collectionId: '1',
    image: 'https://images.pexels.com/photos/1974508/pexels-photo-1974508.jpeg',
    likes: 67,
    createdAt: new Date('2024-04-10'),
    updatedAt: new Date('2024-11-25'),
    isActive: true,
    variants: [
      {
        id: 'v6',
        articleId: '3',
        name: 'Pot de Fleurs Design - Blanc',
        sku: 'PFD-WHT-001',
        price: 24.99,
        stock: 50,
        isDefault: true,
        attributes: [
          { id: 'a14', name: 'Couleur', value: 'Blanc', type: 'color', hexColor: '#FFFFFF' },
          { id: 'a15', name: 'Matériau', value: 'Céramique', type: 'material' },
        ],
        createdAt: new Date('2024-04-10'),
        updatedAt: new Date('2024-11-25'),
        isActive: true,
      },
    ],
  },
  {
    id: '4',
    title: 'Casque Audio Bluetooth',
    description: 'Casque sans fil avec réduction de bruit active et autonomie 30h',
    basePrice: 149.99,
    categoryId: '1',
    collectionId: '2',
    image: 'https://images.pexels.com/photos/3587478/pexels-photo-3587478.jpeg',
    likes: 234,
    createdAt: new Date('2024-07-05'),
    updatedAt: new Date('2024-12-02'),
    isActive: true,
    variants: [
      {
        id: 'v7',
        articleId: '4',
        name: 'Casque Audio Bluetooth - Noir',
        sku: 'CAB-BLK-001',
        price: 149.99,
        stock: 30,
        isDefault: true,
        attributes: [
          { id: 'a16', name: 'Couleur', value: 'Noir', type: 'color', hexColor: '#000000' },
        ],
        createdAt: new Date('2024-07-05'),
        updatedAt: new Date('2024-12-02'),
        isActive: true,
      },
    ],
  },
  {
    id: '5',
    title: 'Robe d\'été Fleurie',
    description: 'Robe légère parfaite pour l\'été avec motifs floraux',
    basePrice: 45.99,
    categoryId: '2',
    collectionId: '2',
    image: 'https://images.pexels.com/photos/985635/pexels-photo-985635.jpeg',
    likes: 178,
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-11-30'),
    isActive: true,
    variants: [
      {
        id: 'v8',
        articleId: '5',
        name: 'Robe d\'été Fleurie - Rose M',
        sku: 'REF-PNK-M',
        price: 45.99,
        stock: 75,
        isDefault: true,
        attributes: [
          { id: 'a17', name: 'Couleur', value: 'Rose', type: 'color', hexColor: '#FFC0CB' },
          { id: 'a18', name: 'Taille', value: 'M', type: 'size' },
        ],
        createdAt: new Date('2024-05-15'),
        updatedAt: new Date('2024-11-30'),
        isActive: true,
      },
    ],
  },
];

export const clients: Client[] = [
  {
    id: '1',
    name: 'Marie Dubois',
    email: 'marie.dubois@email.com',
    phone: '+33 1 23 45 67 89',
    address: '123 Rue de la Paix, 75001 Paris',
    totalOrders: 12,
    totalSpent: 1245.67,
    lastOrderDate: new Date('2024-11-25'),
    isActive: true,
  },
  {
    id: '2',
    name: 'Jean Martin',
    email: 'jean.martin@email.com',
    phone: '+33 2 34 56 78 90',
    address: '456 Avenue des Champs, 69000 Lyon',
    totalOrders: 8,
    totalSpent: 892.34,
    lastOrderDate: new Date('2024-11-20'),
    isActive: true,
  },
  {
    id: '3',
    name: 'Sophie Laurent',
    email: 'sophie.laurent@email.com',
    phone: '+33 3 45 67 89 01',
    address: '789 Boulevard Saint-Michel, 13000 Marseille',
    totalOrders: 15,
    totalSpent: 2134.89,
    lastOrderDate: new Date('2024-12-01'),
    isActive: true,
  },
  {
    id: '4',
    name: 'Pierre Durand',
    email: 'pierre.durand@email.com',
    phone: '+33 4 56 78 90 12',
    address: '321 Rue de Rivoli, 31000 Toulouse',
    totalOrders: 6,
    totalSpent: 567.23,
    lastOrderDate: new Date('2024-11-18'),
    isActive: true,
  },
];

export const salesData: SalesData[] = [
  { month: 'Jan', sales: 45, revenue: 4500 },
  { month: 'Fév', sales: 52, revenue: 5200 },
  { month: 'Mar', sales: 61, revenue: 6100 },
  { month: 'Avr', sales: 58, revenue: 5800 },
  { month: 'Mai', sales: 67, revenue: 6700 },
  { month: 'Jun', sales: 73, revenue: 7300 },
  { month: 'Jul', sales: 81, revenue: 8100 },
  { month: 'Aoû', sales: 78, revenue: 7800 },
  { month: 'Sep', sales: 85, revenue: 8500 },
  { month: 'Oct', sales: 92, revenue: 9200 },
  { month: 'Nov', sales: 87, revenue: 8700 },
  { month: 'Déc', sales: 95, revenue: 9500 },
];

export const categoryStats: CategoryStats[] = [
  { name: 'Électronique', count: 45, percentage: 35 },
  { name: 'Vêtements', count: 38, percentage: 30 },
  { name: 'Maison & Jardin', count: 32, percentage: 25 },
  { name: 'Autres', count: 13, percentage: 10 },
];